[PHP]
memory_limit = 512M
upload_max_filesize = 20M
post_max_size = 20M
max_execution_time = 600
max_input_time = 600
date.timezone = Africa/Abidjan

[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2
opcache.save_comments = 1

expose_php = Off

; PHP-FPM specific (will also set via www.conf if needed)
request_terminate_timeout = 600
